version: '3.8'

services:
  puch-mcp-server:
    build: .
    container_name: puch-mcp-chatbot
    restart: unless-stopped
    
    # Environment variables from .env file
    env_file:
      - .env
    
    # Additional environment variables
    environment:
      - LOG_LEVEL=INFO
      - LOG_FILE=puch_chatbot.log
    
    # Volume for persistent logs
    volumes:
      - ./logs:/app/logs
      - ./data:/app/data  # For future data persistence
    
    # Health check
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    
    # Logging configuration
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Add a reverse proxy for HTTP interface (future)
  # nginx:
  #   image: nginx:alpine
  #   container_name: puch-mcp-proxy
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - puch-mcp-server
  #   restart: unless-stopped

networks:
  default:
    name: puch-mcp-network